In [9]:
import numpy as np
a=np.empty((5,2),dtype=int)
a

array([[-1586689808,         426],
       [    7536756,     4456540],
       [    4980801,     4390971],
       [    6029370,     7471184],
       [    6750319,     6357106]])

In [15]:
a=np.zeros(10,dtype=int)
a[4]=1
print(*a)

0 0 0 0 1 0 0 0 0 0


In [16]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

In [20]:
np.random.rand()

0.5532926236570869

In [37]:
np.random.randint(0,10,size=(4,5))

array([[0, 8, 3, 6, 0],
       [5, 9, 3, 5, 1],
       [1, 6, 4, 6, 9],
       [3, 1, 1, 5, 4]])

In [44]:
import numpy as np
a=np.linspace(0,5,9,dtype=float,endpoint=False)
print(a)
for i in range(1,len(a)):
    print("%0.2f"%(a[i]))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444]
0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


In [57]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
print(*input_[2,:3])
print(*input_[1:4,3])
b=input_[2:4,::]
for i in b:
    for j in i:
        print(j,end=" ")
print()
a= input_[1:3,1:3]
for i in a:
    print(*i,end=" ")


11 12 13
9 14 19
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 

In [11]:
import numpy as np
a=np.array([1,2,0,0,4,0])
ind=np.where(a!=0)
for i in ind:
    print(*i)

0 1 4


In [15]:
import numpy as np
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
ind=np.where(a%2!=0)
a[ind]=-1
print(*a)

-1 2 -1 4 -1 6 -1 8 -1 10


In [23]:
import numpy as np
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
ind=np.where((a>=3) & (a<=8))
a[ind]=-a[ind]
for i in a:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


In [5]:
import numpy as np
a=np.array([[21,20,19,18,17],[16,15,14,13,12],[11,10,9,8,7],[6,5,4,3,2]])
ind=a[:,1].argsort()
print(a)
a=a[ind]
print()
print(a)

[[21 20 19 18 17]
 [16 15 14 13 12]
 [11 10  9  8  7]
 [ 6  5  4  3  2]]

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


In [17]:
import numpy as np
import csv
file_obj=open("terrorismData.csv",encoding="utf-8")
file_data=csv.DictReader(file_obj,skipinitialspace=True)
killed=[]
country=[]
for row in file_data:
    killed.append(row["Killed"])
    country.append(row["Country"])
    
np_killed=np.array(killed)
np_killed[np_killed==""]="0.0"
np_killed=np.array(np_killed, dtype=float)

np_country = np.array(country)
bool_arr = np_country=="United States"
np_killed=np_killed[bool_arr]
print(np_killed)


[0. 0. 0. ... 0. 0. 1.]


In [34]:
import numpy as np
import csv
file_obj=open("terrorismData.csv",encoding="utf-8")
file_data=csv.DictReader(file_obj,skipinitialspace=True)

arr=[]
for row in file_data:
    arr.append(row["Day"])
np_arr=np.array(arr,dtype=int)
ind=np.where((np_arr >= 10) & (np_arr <= 20))
np_arr=np_arr[ind]
print(np_arr.size)


66330


In [49]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
import csv

path= "terrorismData.csv"
casualty=[]
month=[]
city=[]

## Here we lter out the data

with open(path, 'r',encoding='ISO-8859-1') as data:
     reader = csv.DictReader(data)
     for row in reader:
         if row['State']=='Jammu and Kashmir' and row['Year']=='1999':
             if row['Month']=='5' or row['Month']=='6' or row['Month']==7:
                 city.append([row['City'],row['Group']])
                 casualty.append([row['Killed'],row['Wounded']])
                
npcasualty=np.array(casualty)
npcity=np.array(city)

## Coverting the empty values present in Killed and wounded feature to Zero
npcasualty[npcasualty=='']=0

## Converting the string value to oat
npcasualty=np.array(npcasualty,dtype=float)

## Now Summing up the Killed and wounded feature to nd out the casualty
npcasualty=np.sum(npcasualty,axis=1)
index=np.argmax(npcasualty)
print(int(npcasualty[index]),npcity[index][0],npcity[index][1])


22 Kargil District Separatists


In [50]:
import numpy as np
import csv
path= "terrorismData.csv"
killed=[]
wounded=[]

with open(path, 'r',encoding='ISO-8859-1') as file_obj:
     file_data = csv.DictReader(file_obj,skipinitialspace=True)
     for row in file_data:
        if row["State"]=="Jharkhand" or row["State"]=="Odisha" or row["State"]=="Andhra Pradesh" or row["State"]=="Chhattisgarh":
            killed.append(row["Killed"])
            wounded.append(row["Wounded"])
np_killed=np.array(killed)
np_killed[np_killed==""]="0"
np_killed=np.array(np_killed,dtype=float)
np_wounded=np.array(wounded)
np_wounded[np_wounded==""]="0"
np_wounded=np.array(np_wounded,dtype=float)


casualty=np_killed+np_wounded
print(int(np.sum(casualty)))

5628
