In [9]:
import numpy as np
a=np.empty((5,2),dtype=int)
a

array([[-1586689808,         426],
       [    7536756,     4456540],
       [    4980801,     4390971],
       [    6029370,     7471184],
       [    6750319,     6357106]])

In [15]:
a=np.zeros(10,dtype=int)
a[4]=1
print(*a)

0 0 0 0 1 0 0 0 0 0


In [16]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

In [20]:
np.random.rand()

0.5532926236570869

In [37]:
np.random.randint(0,10,size=(4,5))

array([[0, 8, 3, 6, 0],
       [5, 9, 3, 5, 1],
       [1, 6, 4, 6, 9],
       [3, 1, 1, 5, 4]])

In [44]:
import numpy as np
a=np.linspace(0,5,9,dtype=float,endpoint=False)
print(a)
for i in range(1,len(a)):
    print("%0.2f"%(a[i]))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444]
0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


In [57]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
print(*input_[2,:3])
print(*input_[1:4,3])
b=input_[2:4,::]
for i in b:
    for j in i:
        print(j,end=" ")
print()
a= input_[1:3,1:3]
for i in a:
    print(*i,end=" ")


11 12 13
9 14 19
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 

In [11]:
import numpy as np
a=np.array([1,2,0,0,4,0])
ind=np.where(a!=0)
for i in ind:
    print(*i)

0 1 4


In [15]:
import numpy as np
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
ind=np.where(a%2!=0)
a[ind]=-1
print(*a)

-1 2 -1 4 -1 6 -1 8 -1 10


In [23]:
import numpy as np
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
ind=np.where((a>=3) & (a<=8))
a[ind]=-a[ind]
for i in a:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


In [5]:
import numpy as np
a=np.array([[21,20,19,18,17],[16,15,14,13,12],[11,10,9,8,7],[6,5,4,3,2]])
ind=a[:,1].argsort()
print(a)
a=a[ind]
print()
print(a)

[[21 20 19 18 17]
 [16 15 14 13 12]
 [11 10  9  8  7]
 [ 6  5  4  3  2]]

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


In [17]:
import numpy as np
import csv
file_obj=open("terrorismData.csv",encoding="utf-8")
file_data=csv.DictReader(file_obj,skipinitialspace=True)
killed=[]
country=[]
for row in file_data:
    killed.append(row["Killed"])
    country.append(row["Country"])
    
np_killed=np.array(killed)
np_killed[np_killed==""]="0.0"
np_killed=np.array(np_killed, dtype=float)

np_country = np.array(country)
bool_arr = np_country=="United States"
np_killed=np_killed[bool_arr]
print(np_killed)


[0. 0. 0. ... 0. 0. 1.]


In [34]:
import numpy as np
import csv
file_obj=open("terrorismData.csv",encoding="utf-8")
file_data=csv.DictReader(file_obj,skipinitialspace=True)

arr=[]
for row in file_data:
    arr.append(row["Day"])
np_arr=np.array(arr,dtype=int)
ind=np.where((np_arr >= 10) & (np_arr <= 20))
np_arr=np_arr[ind]
print(np_arr.size)


66330


In [49]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
import csv

path= "terrorismData.csv"
casualty=[]
month=[]
city=[]

## Here we lter out the data

with open(path, 'r',encoding='ISO-8859-1') as data:
     reader = csv.DictReader(data)
     for row in reader:
         if row['State']=='Jammu and Kashmir' and row['Year']=='1999':
             if row['Month']=='5' or row['Month']=='6' or row['Month']==7:
                 city.append([row['City'],row['Group']])
                 casualty.append([row['Killed'],row['Wounded']])
                
npcasualty=np.array(casualty)
npcity=np.array(city)

## Coverting the empty values present in Killed and wounded feature to Zero
npcasualty[npcasualty=='']=0

## Converting the string value to oat
npcasualty=np.array(npcasualty,dtype=float)

## Now Summing up the Killed and wounded feature to nd out the casualty
npcasualty=np.sum(npcasualty,axis=1)
index=np.argmax(npcasualty)
print(int(npcasualty[index]),npcity[index][0],npcity[index][1])


22 Kargil District Separatists


In [50]:
import numpy as np
import csv
path= "terrorismData.csv"
killed=[]
wounded=[]

with open(path, 'r',encoding='ISO-8859-1') as file_obj:
     file_data = csv.DictReader(file_obj,skipinitialspace=True)
     for row in file_data:
        if row["State"]=="Jharkhand" or row["State"]=="Odisha" or row["State"]=="Andhra Pradesh" or row["State"]=="Chhattisgarh":
            killed.append(row["Killed"])
            wounded.append(row["Wounded"])
np_killed=np.array(killed)
np_killed[np_killed==""]="0"
np_killed=np.array(np_killed,dtype=float)
np_wounded=np.array(wounded)
np_wounded[np_wounded==""]="0"
np_wounded=np.array(np_wounded,dtype=float)


casualty=np_killed+np_wounded
print(int(np.sum(casualty)))

5628


In [3]:
import csv
import numpy as np
with open("terrorismData.csv",'r',encoding='ISO-8859-1') as f:
    ff=csv.DictReader(f,skipinitialspace=True)
    killed=[]
    wounded=[]
    city=[]
    group=[]
    for row in ff:
        if ((int(float(row["Month"]))>=5) and (int(float(row["Month"]))<=7) and (row["Year"]=='1999') and row['State']=='Jammu and Kashmir'):
            a=row["Killed"]
            killed.append(a)
            a=row["Wounded"]
            wounded.append(a)
            a=row["City"]
            city.append(a)
            a=row["Group"]
            group.append(a)
        
np_killed=np.array(killed)
np_wounded=np.array(wounded)
np_city=np.array(city)
np_group=np.array(group)

np_wounded[np_wounded=='']='0.0'
np_killed[np_killed=='']='0.0'
np_killed=np.array(np_killed,dtype=float)
np_killed=np.array(np_killed,dtype=int)
np_wounded=np.array(np_wounded,dtype=float)
np_wounded=np.array(np_wounded,dtype=int)

np_casualty=np_killed+np_wounded
inx=np.argmax(np_casualty)
print(np_casualty[inx],np_city[inx],np_group[inx])


22 Kargil District Separatists


In [6]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
import csv
import operator

file_obj=open('terrorismData.csv',encoding='utf8')
data=csv.DictReader(file_obj, skipinitialspace= True )

killed = []
wounded = []
city=[]
cas={}

for row in data:
    if row['Country']=='India' and row['City']!='Unknown':
        killed.append(row['Killed'])
        wounded.append(row['Wounded'])
        city.append(row['City'])
        
np_killed=np.array(killed)
np_killed[np_killed=='']='0.0'
np_killed=np.array(np_killed, dtype='float')
np_wounded=np.array(wounded)
np_wounded[np_wounded=='']='0.0'
np_wounded=np.array(np_wounded, dtype='float')
np_city=np.array(city)


a =np.array(np_city)
unique, counts = np.unique(a, return_counts=True)
count = dict(zip(unique, counts))
print(np_city)
print(unique)
print(counts)
#sorted_d = dict(sorted(count.items(), key=operator.itemgetter(1),reverse=True)[:5])
#print(sorted_d)

#np_casualty=np.array(np_killed+np_wounded, dtype='int')
#print(np_casualty)

#keys=sorted_d.keys()
#value=np_casualty


['New Delhi' 'Samastipur' 'New Delhi' ... 'Lethapora' 'Hungrum' 'Imphal']
['Aankro' 'Aatpal' 'Abhapalli' ... 'runikhata' 'srinagar' 'uri']
[1 1 1 ... 1 4 1]


In [2]:
## Open and read data file as specified in the question
## Print the required output in given format

import pandas as pd

tdata = pd.read_csv("terrorismData.csv")
df = tdata.copy()
df['Casualty'] = df['Killed']+df['Wounded']
rc1 = df[(df.Country=='India')]
#df[df.Wounded==np.nan]
rc1 = rc1[(rc1.State=='Jharkhand') | (rc1.State=='Odisha') |(rc1.State=='Andhra Pradesh') |(rc1.State=='Chhattisgarh')]
totalc = int(rc1.Casualty.sum())
years = rc1.Year.max()-rc1.Year.min()

freq1= totalc//47

rc2 = df[(df.State=='Jammu and Kashmir')]
totalc2 = int(rc2.Casualty.sum())
years2 = rc2.Year.max()-rc2.Year.min()

freq2= totalc2//47
print(freq1,freq2)

115 261


In [3]:
years2

33

In [6]:
years

38

In [4]:
rc2.Year.max()

2017

In [5]:
rc2.Year.min()

1984

In [2]:
import numpy as np
import csv
file_obj = open('terrorismData.csv', encoding="utf-8")
file_data = csv.DictReader(file_obj, skipinitialspace = True)

killed = []
country = []
for row in file_data:
    killed.append(row['Killed'])
    country.append(row['Country'])

np_killed = np.array(killed)
np_killed[np_killed == ''] = '0.0'
np_killed = np.array(np_killed, dtype = float)
np_killed = np.array(np_killed, dtype = int)
np_country = np.array(country)
bool_country = np_country == 'United States'
ans = np_killed[bool_country]
for i in ans:
    print(i)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
4
0
1
1
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0


In [1]:
import csv

with open('year2017.csv', newline='') as csvfile:
    data = csv.DictReader(csvfile)
    data_list = list(data)
    for row in range(1,11):
        print(data_list[row][3])

FileNotFoundError: [Errno 2] No such file or directory: 'year2017.csv'

In [14]:
## Open and read data file as specified in the question
## Print the required output in given format
import csv
import numpy as np

with open("terrorismData.csv",encoding='ISO-8859-1') as file:
    file_list= csv.DictReader(file, skipinitialspace=True)
    killed=[]
    wounded=[]
    city=[]
    
    for i in file_list:
        if i["Country"]=="India":
            killed.append(i["Killed"])
            wounded.append(i["Wounded"])
            city.append(i["City"])
        
np_kill= np.array(killed)
np_wounded=np.array(wounded)
np_kill[np_kill=='']='0.0'
np_wounded[np_wounded=='']='0.0'
np_kill= np.array(np_kill,dtype=float)
np_wounded= np.array(np_wounded,dtype=float)
np_casualty= np_kill+np_wounded
np_city=np.array(city)


def cityCasualty(cityarr,casualtyarr):
    arr=[]
    unique=np.unique(cityarr)
    for i in unique:
        index=np.where(cityarr==i)
        sumCasualty= casualtyarr[index].sum()
        arr.append([sumCasualty,i])
    arr.sort(reverse=True)
    return arr
arr=cityCasualty(np_city,np_casualty)
for i in range(6):
    if arr[i][1]!='Unknown':
        print(arr[i][1],int(arr[i][0]))

Srinagar 3134
New Delhi 2095
Mumbai 2016
Jammu 1119
Guwahati 822


In [18]:
## Open and read data file as specified in the question
## Print the required output in given format
import csv
import numpy as np

with open("terrorismData.csv",encoding='ISO-8859-1') as file:
    file_list= csv.DictReader(file, skipinitialspace=True)
    killed=[]
    wounded=[]
    city=[]
    
    for i in file_list:
        if i["Country"]=="India":
            killed.append(i["Killed"])
            wounded.append(i["Wounded"])
            city.append(i["City"])
        
np_kill= np.array(killed)
np_wounded=np.array(wounded)
np_kill[np_kill=='']='0.0'
np_wounded[np_wounded=='']='0.0'
np_kill= np.array(np_kill,dtype=float)
np_wounded= np.array(np_wounded,dtype=float)
np_casualty= np_kill+np_wounded
np_city=np.array(city)
bool_city= np_city != "Unknown"
np_casualty= np_casualty[bool_city]
np_city=np_city[bool_city]
index = np_casualty.argsort()[-5:]
for i in index:
    print(np_city[i]," ",int(np_casualty[i]))
index

New Delhi   210
Chennai   232
Jhargam   255
Dispur   272
Mumbai   1005


array([3591,  258, 5358, 4292, 3689], dtype=int64)

In [19]:
import pandas as pd
column_name=['SepalLength','SepalWidth','PetalLength','PetalWidth','Species']
iris=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',names=column_name)
df=iris.copy()
p=df[df.Species =="Iris-virginica"]
p=p[p.PetalLength>1.5]
p=p.values
for i in range(p.shape[0]):
    for j in range(p.shape[1]):
        print(p[i][j],end=" ")
    print()

6.3 3.3 6.0 2.5 Iris-virginica 
5.8 2.7 5.1 1.9 Iris-virginica 
7.1 3.0 5.9 2.1 Iris-virginica 
6.3 2.9 5.6 1.8 Iris-virginica 
6.5 3.0 5.8 2.2 Iris-virginica 
7.6 3.0 6.6 2.1 Iris-virginica 
4.9 2.5 4.5 1.7 Iris-virginica 
7.3 2.9 6.3 1.8 Iris-virginica 
6.7 2.5 5.8 1.8 Iris-virginica 
7.2 3.6 6.1 2.5 Iris-virginica 
6.5 3.2 5.1 2.0 Iris-virginica 
6.4 2.7 5.3 1.9 Iris-virginica 
6.8 3.0 5.5 2.1 Iris-virginica 
5.7 2.5 5.0 2.0 Iris-virginica 
5.8 2.8 5.1 2.4 Iris-virginica 
6.4 3.2 5.3 2.3 Iris-virginica 
6.5 3.0 5.5 1.8 Iris-virginica 
7.7 3.8 6.7 2.2 Iris-virginica 
7.7 2.6 6.9 2.3 Iris-virginica 
6.0 2.2 5.0 1.5 Iris-virginica 
6.9 3.2 5.7 2.3 Iris-virginica 
5.6 2.8 4.9 2.0 Iris-virginica 
7.7 2.8 6.7 2.0 Iris-virginica 
6.3 2.7 4.9 1.8 Iris-virginica 
6.7 3.3 5.7 2.1 Iris-virginica 
7.2 3.2 6.0 1.8 Iris-virginica 
6.2 2.8 4.8 1.8 Iris-virginica 
6.1 3.0 4.9 1.8 Iris-virginica 
6.4 2.8 5.6 2.1 Iris-virginica 
7.2 3.0 5.8 1.6 Iris-virginica 
7.4 2.8 6.1 1.9 Iris-virginica 
7.9 3.8 

In [1]:
import pandas as pd
data = pd.read_csv('terrorismData.csv')
df=data.copy()
df = df[(df.Country == 'India')  & (df.Year > 2013)].reset_index(drop = True)
for i in range(len(df)):
    if (df.Year[i] == 2014 and df.Month[i] < 5) or (df.Year[i] == 2014 and df.Day[i] < 26 and df.Month[i] ==5):
        df.drop(i,inplace=True)
c=df.Country.describe().freq
d=df[df.Group !='Unknown']
print(c,d.Group.describe().top)

3336 Maoists
